services:
  - type: web
    name: lumeo-photo-organizer-backend
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    workingDirectory: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0